/**
 * U-012: the cue manifest — every game event that says something, how it is
 * heard, which recorded lines it needs, and which of those clips nobody has
 * recorded yet. Written by `pnpm gen:voice` to `docs/audio/voice-cues.md`
 * from the data (`voices.json`, `callouts.json`) and what was processed
 * (`renders.json`); `voice.test.ts` fails when the committed file is not
 * what the data says now.
 *
 * A clip is one line in one voice and one treatment: `<profile>/<line>.<style>.<treatment>`,
 * the key `renders.json` lists. A radio cue needs its lines dry (a squadmate
 * near) and radio (one far); a body's sound or an enemy's shout only dry —
 * neither is ever on the radio.
 */
import { fileURLToPath } from 'node:url';
import {
  CALLOUTS,
  CALLOUT_EVENTS,
  type CalloutRouteId,
  type CalloutsConfig,
  VOICES,
  type VoiceTreatment,
  type VoicesConfig,
  passFile,
  sectionProfiles,
} from '@sandline/shared';
import type { VoiceRendersManifest } from './renders.ts';

export const VOICE_CUES_FILE = fileURLToPath(new URL('../../../../docs/audio/voice-cues.md', import.meta.url));

/** The treatments a route is heard in. */
const TREATMENTS: Record<CalloutRouteId, readonly VoiceTreatment[]> = { radio: ['dry', 'radio'], body: ['dry'], shout: ['dry'] };

const HEARD: Record<CalloutRouteId, string> = {
  radio: 'squad dialogue: your own soldier as your own; a squadmate near you where they stand, dry; one farther off over the radio, one voice at a time',
  body: 'a body’s own sound: where the body is, never over the radio; involuntary, so it neither waits for nor holds up the soldier’s words',
  shout: 'an enemy calling out: where it stands, dry, in the enemy’s voices; never over the radio',
};

export function voiceCuesMarkdown(renders: Pick<VoiceRendersManifest, 'lines'>, voices: VoicesConfig = VOICES, callouts: CalloutsConfig = CALLOUTS): string {
  const recorded = (key: string) => (renders.lines[key]?.length ?? 0) > 0;
  // Every clip a cue needs, by line: which cues, which voices, which treatments.
  const needs = new Map<string, { style: string; cues: string[]; treatments: Set<VoiceTreatment> }>();
  for (const id of CALLOUT_EVENTS) {
    const def = callouts.events[id];
    for (const { line, style } of def.lines) {
      const need = needs.get(line) ?? { style, cues: [], treatments: new Set<VoiceTreatment>() };
      if (!need.cues.includes(id)) need.cues.push(id);
      for (const t of TREATMENTS[def.route]) if (voices.treatments.includes(t)) need.treatments.add(t);
      needs.set(line, need);
    }
  }
  let clips = 0;
  let have = 0;
  const lineRows: string[] = [];
  for (const section of voices.sections) {
    for (const style of section.render) {
      const lines = style === 'hurt' ? section.hurt : section.lines;
      for (const line of lines) {
        const need = needs.get(line);
        if (!need || need.style !== style) {
          lineRows.push(`| \`${line}\` | \`${passFile(section.id, style)}\` | — | not used by a cue yet |`);
          continue;
        }
        const missing: string[] = [];
        for (const profile of sectionProfiles(section, voices)) {
          for (const t of need.treatments) {
            clips += 1;
            if (recorded(`${profile.id}/${line}.${style}.${t}`)) have += 1;
            else missing.push(`${profile.id} ${t}`);
          }
        }
        const status = missing.length === 0 ? 'recorded' : missing.length === sectionProfiles(section, voices).length * need.treatments.size ? `**all missing** (${sectionProfiles(section, voices).map((p) => p.id).join(', ')} × ${[...need.treatments].join(', ')})` : `missing: ${missing.join(', ')}`;
        lineRows.push(`| \`${line}\` | \`${passFile(section.id, style)}\` | ${need.cues.map((c) => `\`${c}\``).join(', ')} | ${status} |`);
      }
    }
  }
  const routeRows = (Object.keys(callouts.routes) as CalloutRouteId[]).map((id) => {
    const r = callouts.routes[id];
    const carries = id === 'radio' ? `${callouts.radioBeyondM} m in the open, then the radio` : `${r.audibleM} m`;
    const stand = r.placeholder === null ? 'silence' : `\`${r.placeholder}\` — a PLACEHOLDER, not a voice`;
    return `| \`${id}\` | ${HEARD[id]} | ${carries} | ${r.gainDb} dB | ${stand} |`;
  });
  const cueRows = CALLOUT_EVENTS.map((id) => {
    const def = callouts.events[id];
    const who = def.route === 'shout' ? 'an enemy' : def.self ? 'a squadmate or you' : 'a squadmate';
    return `| \`${id}\` | \`${def.route}\` | ${who} | ${def.lines.map((l) => `\`${l.line}\` (${l.style})`).join(', ')} | ${def.cooldown} s, ${def.scope} | ${def.priority} |`;
  });
  return [
    '# Voice cues — what each game event says, and what is still missing',
    '',
    '<!-- GENERATED BY packages/tools/src/gen-voice.ts (packages/tools/src/voice/cues.ts) — DO NOT EDIT BY HAND. Regenerate with `pnpm gen:voice`. -->',
    '',
    'Every game event that says something (U-012), how it is heard, and every recorded clip it needs.',
    'The lines themselves are recorded from [voice-script.md](voice-script.md); the IDs here are the ones it names.',
    `**${have} of ${clips} clips recorded.** Until a clip is recorded its cue plays its route's placeholder, below.`,
    '',
    '## Routes',
    '',
    '| Route | Heard as | Carries | Level | Until recorded |',
    '|---|---|---|---|---|',
    ...routeRows,
    '',
    '## Cues',
    '',
    '| Event | Route | Said by | Lines (pass) | Cooldown | Priority |',
    '|---|---|---|---|---|---|',
    ...cueRows,
    '',
    '## Clips, line by line',
    '',
    'A clip is one line in one voice (`s0`–`s5` the squad’s six slots, `e0`… the enemy’s) and one treatment.',
    '',
    '| Line | Recording pass | Cues | Clips |',
    '|---|---|---|---|',
    ...lineRows,
    '',
  ].join('\n');
}
