// GENERATED BY packages/tools/src/gen-nav.ts — DO NOT EDIT BY HAND.
// Regenerate with `pnpm gen:nav` after changing a world, MoveConfig or the hitbox.
import type { BakedNav } from './types.ts';
import { BAKED as W0 } from './range.ts';

/** Every committed bake, by world id. */
export const BAKED_NAV: Readonly<Record<string, BakedNav>> = {
  'range': W0,
};
