/**
 * Renders every sound recipe and commits it (T-2.44, ADR-017).
 *
 * Writes `packages/client/public/audio/<id>.<variant>.wav` for every recipe in
 * `shared/src/data/audio/sounds.json`, plus `renders.json`: the inputs hash,
 * and each file's size, digest and measured peak, loudness and length.
 * Files for sounds no longer in the recipes are removed. Seeded and offline:
 * run it twice and nothing changes.
 *
 * `audio.test.ts` fails when a recipe or the DSP changes without this being
 * re-run, and when a render leaves its recipe's bounds or clips.
 *
 * Run: pnpm gen:audio
 */
import { mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { SOUNDS, soundFile } from '@sandline/shared';
import { measure, renderSound, toPcm16, wavBytes } from './audio/render.ts';
import { AUDIO_DIR, RENDERS_FILE, type RendersManifest, audioInputsHash, round2, sha256 } from './audio/renders.ts';

mkdirSync(AUDIO_DIR, { recursive: true });
const manifest: RendersManifest = {
  $comment: 'GENERATED BY packages/tools/src/gen-audio.ts — DO NOT EDIT BY HAND. Regenerate with `pnpm gen:audio` after changing a recipe or the DSP.',
  inputsHash: audioInputsHash(),
  sampleRate: SOUNDS.sampleRate,
  sounds: {},
};
const written = new Set<string>(['renders.json']);
let failures = 0;
for (const [id, def] of [...SOUNDS.sounds.entries()].sort(([a], [b]) => (a < b ? -1 : 1))) {
  manifest.sounds[id] = [];
  for (let v = 0; v < def.variants; v += 1) {
    const pcm = toPcm16(renderSound(def, v, SOUNDS.sampleRate));
    const bytes = wavBytes(pcm, SOUNDS.sampleRate);
    const file = soundFile(id, v);
    writeFileSync(new URL(file, AUDIO_DIR), bytes);
    written.add(file);
    const m = measure(pcm, SOUNDS.sampleRate);
    manifest.sounds[id]!.push({ file, bytes: bytes.length, sha256: sha256(bytes), peakDb: round2(m.peakDb), rmsDb: round2(m.rmsDb), seconds: round2(m.seconds) });
    const b = def.bounds;
    const out = [
      m.clipped > 0 ? `${m.clipped} clipped samples` : '',
      m.peakDb < b.peakDb[0] || m.peakDb > b.peakDb[1] ? `peak ${m.peakDb.toFixed(2)} dB outside [${b.peakDb.join(', ')}]` : '',
      m.rmsDb < b.rmsDb[0] || m.rmsDb > b.rmsDb[1] ? `rms ${m.rmsDb.toFixed(2)} dB outside [${b.rmsDb.join(', ')}]` : '',
      m.seconds < b.seconds[0] || m.seconds > b.seconds[1] ? `length ${m.seconds.toFixed(3)} s outside [${b.seconds.join(', ')}]` : '',
    ].filter((s) => s !== '');
    console.log(`${file}: ${bytes.length} bytes, peak ${m.peakDb.toFixed(2)} dB, rms ${m.rmsDb.toFixed(2)} dB, ${m.seconds.toFixed(3)} s${out.length ? `  OUT OF BOUNDS: ${out.join('; ')}` : ''}`);
    if (out.length) failures += 1;
  }
}
for (const name of readdirSync(AUDIO_DIR)) {
  if (!written.has(name) && name.endsWith('.wav')) rmSync(new URL(name, AUDIO_DIR));
}
writeFileSync(RENDERS_FILE, `${JSON.stringify(manifest, null, 2)}\n`);
if (failures > 0) {
  console.error(`${failures} render(s) outside their recipe's bounds — fix the recipe or its bounds`);
  process.exit(1);
}
