/**
 * Generates packages/server/src/ai/nav/spikeMesh.ts (T-3.01).
 *
 * The spike's claim is that ONE set of exported bytes loads and answers the
 * same path query in Node and in every browser engine the in-page session
 * runs in. So the bytes are baked once, here, in Node, and committed; the
 * cross-runtime test loads that literal rather than re-baking per engine. The
 * Node path length is committed beside it as the reference each engine's
 * result is compared against.
 *
 * Run: pnpm gen:nav-spike
 */
import { writeFileSync } from 'node:fs';
import { NavMesh, initNav, pathLength } from '../../server/src/ai/nav/NavMesh.ts';
import {
  SPIKE_BOXES,
  SPIKE_FLOOR_HALF_EXTENT,
  SPIKE_FROM,
  SPIKE_TO,
  bakeNavMesh,
  boxSoup,
} from './nav/bake.ts';

const bytes = await bakeNavMesh(boxSoup(SPIKE_FLOOR_HALF_EXTENT, SPIKE_BOXES));
await initNav();
const mesh = NavMesh.load(bytes);
const path = mesh.path(SPIKE_FROM, SPIKE_TO);
if (!path) throw new Error('spike mesh has no path between the spike points');
const length = pathLength(path.points);
mesh.destroy();

const base64 = Buffer.from(bytes).toString('base64');
const lines = base64.match(/.{1,100}/g) ?? [];
const out = `// GENERATED BY packages/tools/src/gen-nav-spike.ts — DO NOT EDIT BY HAND.
// Regenerate with \`pnpm gen:nav-spike\` if the spike geometry or agent changes.
/** The T-3.01 spike mesh, exported by Detour, base64. ${bytes.length} bytes. */
export const SPIKE_MESH_BASE64 =
  ${lines.map((l) => `'${l}'`).join(' +\n  ')};

export const SPIKE_FROM = ${JSON.stringify(SPIKE_FROM)} as const;
export const SPIKE_TO = ${JSON.stringify(SPIKE_TO)} as const;

/** Path length between the spike points, computed in Node from these bytes. */
export const SPIKE_NODE_PATH_LENGTH = ${String(length)};
`;

const target = new URL('../../server/src/ai/nav/spikeMesh.ts', import.meta.url);
writeFileSync(target, out);
console.log(`wrote ${target.pathname}: ${bytes.length} bytes, path ${length.toFixed(3)} m`);
