/**
 * Turns the voice uploads into game lines and commits them (T-2.48, ADR-017).
 *
 * Reads every speaker under `assets/voice/raw/` (see
 * `docs/audio/voice-script.md` for what they recorded and how), and writes
 * `packages/client/public/audio/voice/<profile>/<line>.<style>.<treatment>.<variant>.wav`
 * for every slot's profile, plus `renders.json`: the inputs hash, what was
 * found in each upload, and each line's size, digest and measured loudness.
 * Lines no longer made are removed. Seeded and offline: run it twice and
 * nothing changes.
 *
 * Exits 1, naming it, on a speaker without consent, a file the script does
 * not name, a pass whose takes do not match the script, or a line off its
 * loudness target. `voice.test.ts` fails when an upload, the voice data or
 * the pipeline changes without this being re-run.
 *
 * Run: pnpm gen:voice
 */
import { mkdirSync, readdirSync, rmSync, rmdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { VOICES } from '@sandline/shared';
import { renderVoices } from './voice/process.ts';
import { RAW_DIR, VOICE_DIR, VOICE_RENDERS_FILE, type VoiceRendersManifest, round2, sha256, voiceInputsHash } from './voice/renders.ts';

let run;
try {
  run = renderVoices(RAW_DIR, VOICES, undefined, (line) => console.log(line));
} catch (e) {
  console.error((e as Error).message);
  process.exit(1);
}

mkdirSync(VOICE_DIR, { recursive: true });
const manifest: VoiceRendersManifest = {
  $comment: 'GENERATED BY packages/tools/src/gen-voice.ts — DO NOT EDIT BY HAND. Regenerate with `pnpm gen:voice` after an upload under assets/voice/raw/, or a change to voices.json or the pipeline.',
  inputsHash: voiceInputsHash(),
  sampleRate: VOICES.sampleRate,
  speakers: run.speakers,
  lines: {},
  missing: run.missing,
};
const written = new Set<string>(['renders.json']);
let failures = 0;
const { targetLufs, toleranceLu, ceilingDb } = VOICES.loudness;
for (const line of run.lines) {
  const path = join(VOICE_DIR, line.file);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, line.wav);
  written.add(line.file);
  (manifest.lines[line.key] ??= []).push({ file: line.file, bytes: line.wav.length, sha256: sha256(line.wav), lufs: round2(line.lufs), peakDb: round2(line.peakDb), seconds: round2(line.seconds) });
  const off = Math.abs(line.lufs - targetLufs) > toleranceLu || line.peakDb > ceilingDb + 0.01;
  if (off) {
    failures += 1;
    console.error(`${line.file}: ${line.lufs.toFixed(2)} LUFS, peak ${line.peakDb.toFixed(2)} dB — target ${targetLufs} ± ${toleranceLu}, ceiling ${ceilingDb}`);
  }
}
/** Remove what was not written this run, and the folders left empty. */
function sweep(dir: string, prefix = ''): void {
  for (const name of readdirSync(dir)) {
    const path = join(dir, name);
    const rel = prefix ? `${prefix}/${name}` : name;
    if (statSync(path).isDirectory()) {
      sweep(path, rel);
      if (readdirSync(path).length === 0) rmdirSync(path);
    } else if (!written.has(rel)) rmSync(path);
  }
}
sweep(VOICE_DIR);
writeFileSync(VOICE_RENDERS_FILE, `${JSON.stringify(manifest, null, 2)}\n`);
console.log(`${run.speakers.length} speaker(s), ${run.lines.length} line file(s)${run.missing.length ? `, ${run.missing.length} line(s) not recorded` : ''}`);
if (failures > 0) {
  console.error(`${failures} line(s) off their loudness target`);
  process.exit(1);
}
