/**
 * Processes every source glTF under `assets/src/` into its web copy and
 * writes the manifest (T-4.02; the steps are `assets/pipeline.ts`).
 *
 *   assets/src/<id>.glb                          the input, whatever made it
 *   packages/client/public/assets/<id>.glb       the web copy, served at assets/<id>.glb
 *   packages/shared/src/data/assets/manifest.json one entry per copy
 *
 * All three are committed, as `gen:nav`'s bakes are: the page loads bytes,
 * never processes. `assets.test.ts` recomputes each input hash, so a source
 * edited without a re-run fails the suite, and re-processes each source to
 * prove the committed copy is exactly what this writes.
 *
 * Run: pnpm gen:assets
 */
import { readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import type { AssetEntry, AssetManifest } from '@sandline/shared';
import { inputHash, processAsset, sha256, statsOfBytes } from './assets/pipeline.ts';

const SRC = new URL('../../../assets/src/', import.meta.url);
const OUT = new URL('../../client/public/assets/', import.meta.url);
const MANIFEST = new URL('../../shared/src/data/assets/manifest.json', import.meta.url);

const sources = readdirSync(SRC)
  .filter((f) => /\.(glb|gltf)$/.test(f))
  .sort();
const assets: AssetEntry[] = [];
for (const name of sources) {
  const id = name.replace(/\.(glb|gltf)$/, '');
  const source = new Uint8Array(readFileSync(new URL(name, SRC)));
  const t0 = performance.now();
  const web = await processAsset(source);
  writeFileSync(new URL(`${id}.glb`, OUT), web);
  const stats = await statsOfBytes(web);
  assets.push({ id, source: `assets/src/${name}`, file: `assets/${id}.glb`, inputHash: inputHash(source), hash: sha256(web), bytes: web.length, ...stats });
  console.log(
    `${id}: ${source.length} → ${web.length} bytes in ${(performance.now() - t0).toFixed(0)} ms; ` +
      `${stats.triangles} triangles, ${stats.bones} bones, ${stats.materials} materials, ` +
      `${stats.textures.map((t) => `${t.width}×${t.height} ${t.format}`).join(', ') || 'no textures'}, ${stats.collision.length} collision boxes`,
  );
}
// A source removed takes its copy with it.
for (const f of readdirSync(OUT)) {
  if (f.endsWith('.glb') && !assets.some((a) => a.file === `assets/${f}`)) rmSync(new URL(f, OUT));
}
const manifest: AssetManifest & { $comment: string } = {
  $comment: 'GENERATED by packages/tools/src/gen-assets.ts — do not edit. Re-run pnpm gen:assets after changing anything in assets/src/.',
  version: 1,
  assets,
};
writeFileSync(MANIFEST, JSON.stringify(manifest, null, 2) + '\n');
