/**
 * Generates packages/shared/src/math/trigTable.ts (T-0.14).
 *
 * WHY THIS IS A BUILD STEP AND NOT A MODULE INITIALISER:
 *
 * Building the table at load time with Math.sin would reproduce the exact bug
 * the table exists to prevent — Math.sin differs between V8, JSC and
 * SpiderMonkey, so each engine would build a *different* table and the
 * simulation would still diverge (ADR-014).
 *
 * So the table is computed once, here, and committed as literal numbers. Every
 * runtime then reads identical bytes. Number literals printed with String()
 * round-trip exactly per ES2018+, so the committed text is lossless.
 *
 * Only a quarter turn is stored; the other three quadrants come from symmetry,
 * which is exact (negation and index reflection only).
 *
 * Run: pnpm gen:trig
 */
import { writeFileSync } from 'node:fs';
import { ANGLE_QUARTER, ANGLE_UNITS } from '../../shared/src/math/angles.ts';

const values: string[] = [];
for (let i = 0; i <= ANGLE_QUARTER; i++) {
  values.push(String(Math.sin((i / ANGLE_UNITS) * Math.PI * 2)));
}

const body = values.join(',\n  ');
const out = `// GENERATED BY packages/tools/src/gen-trig-table.ts — DO NOT EDIT BY HAND.
// Regenerate with \`pnpm gen:trig\` if ANGLE_BITS changes.
//
// sin() sampled over the first quarter turn, inclusive of both endpoints
// (${values.length} entries). Committed as literals rather than computed at load
// so that every engine reads identical values — see ADR-014.

export const QUARTER_SIN: readonly number[] = [
  ${body},
];
`;

const target = new URL('../../shared/src/math/trigTable.ts', import.meta.url);
writeFileSync(target, out);
console.log(`wrote ${values.length} entries to ${target.pathname}`);
