/**
 * Bakes every named world's navmesh and commits it (T-3.03, ADR-006).
 *
 * Writes `packages/server/src/ai/nav/baked/<world>.ts` per world — the
 * Detour export as base64, the agent it was baked for, and the hash of every
 * input that decided it — plus `baked/index.ts`, which maps a world id to its
 * bake. Committed like `gen:trig`'s table: the server and the in-page session
 * load bytes, never bake.
 *
 * `nav.test.ts` recomputes the hash from the live world data and agent, so
 * editing a box, the step height or the capsule radius fails the suite until
 * this is re-run. That is ADR-006's "the level pipeline and the navmesh bake
 * must be wired together or they will silently drift", enforced.
 *
 * Run: pnpm gen:nav
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { WORLD_IDS, requireWorld } from '@sandline/shared';
import { DEFAULT_NAV_AGENT, bakeWorld, navBakeHash } from './nav/bake.ts';

const dir = new URL('../../server/src/ai/nav/baked/', import.meta.url);
mkdirSync(dir, { recursive: true });

const HEADER = `// GENERATED BY packages/tools/src/gen-nav.ts — DO NOT EDIT BY HAND.
// Regenerate with \`pnpm gen:nav\` after changing a world, MoveConfig or the hitbox.`;

const ids = [...WORLD_IDS].sort();
for (const id of ids) {
  const world = requireWorld(id);
  const t0 = performance.now();
  const bytes = await bakeWorld(world);
  const ms = performance.now() - t0;
  const lines = Buffer.from(bytes).toString('base64').match(/.{1,100}/g) ?? [];
  const out = `${HEADER}
import type { BakedNav } from './types.ts';

/** World '${id}': ${bytes.length} bytes of Detour navmesh. */
export const BAKED: BakedNav = {
  world: '${id}',
  hash: '${navBakeHash(world)}',
  agent: ${JSON.stringify(DEFAULT_NAV_AGENT)},
  // An array joined once at load, not a chain of \`+\`: two thousand
  // concatenations nest too deep for a parser to walk.
  base64: [
    ${lines.map((l) => `'${l}'`).join(',\n    ')},
  ].join(''),
};
`;
  writeFileSync(new URL(`${id}.ts`, dir), out);
  console.log(`baked '${id}': ${bytes.length} bytes in ${ms.toFixed(0)} ms`);
}

const index = `${HEADER}
import type { BakedNav } from './types.ts';
${ids.map((id, i) => `import { BAKED as W${i} } from './${id}.ts';`).join('\n')}

/** Every committed bake, by world id. */
export const BAKED_NAV: Readonly<Record<string, BakedNav>> = {
${ids.map((id, i) => `  '${id}': W${i},`).join('\n')}
};
`;
writeFileSync(new URL('index.ts', dir), index);
